# Generated by Django 3.2.5 on 2022-08-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redline_car', '0003_alter_categorie_poids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
